### ISSUE TITLE
Inconsistent keywords for uncertainty quantification

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#117]
Function | Parameter | Values | Supported methods
------------ | ------------- | ---------- | ---------------
`fitmodel` | `uq` | `None, 'cov', 'bootstrap'` |  covariance, bootstrap
`fitparamodel` | `uqanalysis` | `True, False` | covariance 
`fitmultimodel` | `uqanalysis` | `True, False` | covariance
`fitregmodel` | `uqanalysis` | `True, False` | covariance
`snnls` | `uqanalysis` | `True, False` | covariance

To discuss:
- Should the keyword be the same throughout?
- I think `uq` is better `uqanalysis`, since the actual term is "uncertainty quantification", vs. "uncertainty quantification analysis".
- Should all `fit*` functions support bootstrap?

**Comment by luisfabib** [comment]
- Agreed, ``uq=True/False`` instead of `uqanalysis=True/False` would make more sense.
- Bootstrapping should only be supported in the `fitmodel` function and not in any other `fit*` function. The reason is that `fitmodel` is a very rigid model and thus strictly defined quantities of interest returned as outputs. In contrast, the quantities of interest in other `fit*` functions vary depending on the model and the ideas behind the fitting. Covariance must be supported in all fit functions as it is a product of the least-squares fit itself, while bootstrapping is a completely different process and method.

**Comment by stestoll** [comment]
Ok on both points.
