### ISSUE TITLE
`mod` vs `lam` keyword argument

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#277]
`dipolarkernel` takes the modulation depth via `mod` , but the background models take it in `lam`. It might be better to name the two keyword arguments identically. Any counter-arguments? If we rename, `mod` is more descriptive, whereas `lam` is the conventional symbol - what to prefer?

**Comment by luisfabib** [comment]
Actually `mod` is the least descriptive one. Modulation depth is a term only valid for a single-pathway dipolar model. Otherwise, the correct terms are pathway amplitudes symbolized by lambdas hence `lam`. If the existence of the two terms is an issue or unclear, I would rather get rid of the `mod` keyword. 

The same goes for the background functions. If you have a single pathway model, then the lambda doing into the background models would correspond to the modulation depth. Otherwise, the background function is actually a product of the background model with different lambdas being passed to it. In this context, `mod` for the background models would also be incorrect.

**Comment by stestoll** [comment]
`mod` is a shorthand for a two-pathway model, whereas `lam` generally indicates single-pathway amplitudes. That's sufficiently different, and therefore the two differing names make sense.
