### ISSUE TITLE
DeerLab setup.py should not force numpy+mkl and other Gohlke libraries 

### ISSUE THREAD

**Issue by mtessmer** [JeschkeLab/DeerLab#322]
Currently, the default setup.py will install the latest NumPy, SciPy, and cvxopt from the Gohlke unofficial windows binaries repository (for windows computers). Many users may not want to use mkl libraries or require different versions of NumPy, SciPy, or cvxopt for compatibility reasons. DeerLab should check if sufficient versions of these packages are already installed before downloading. It may be prudent to add a warning or recommendation if windows users do not have mkl versions or have older versions of these libraries.

**Comment by luisfabib** [comment]
Good point! A short explanation (not an excuse): back in the day, I set it up for MKL to be the default backend for Numpy-based packages due to the significant speed-up it provided to DeerLab. Since the MKL installation was complicated for me (back then, I was a Python neophyte), I set it such that the default installation for Windows users would be with MKL. 

I fully agree that it should not enforce if users already have a Numpy/Scipy/CVXOpt installation. What do you think would be best? 

1) A simple warning about the presence of pre-existing package installations and DeerLab overwriting them. 
2) A Yes/No prompt during the installation to ask whether to install and/or overwritten with the MKL versions.
3) Add an optional argument ``--mkl`` to the installer to install with the MKL backend on Windows computers and reset the default installation to the base Numpy without MKL.

**Comment by luisfabib** [comment]
My proposal: 
- Standardize the setup.py script to modern standards enabling the distribution of DeerLab via wheels and more safe means.
- Avoids the issues pointed out by Maxx when enforcing Golhke's binaries on users.
- Add an additional script, optional for windows users which automates the upgrade to the MKL-linked packages (basically the script we use now for the installation).

This would extremely simplify the installation of DeerLab and avoid future problems (particularly once I am not 100% dedicated to this project).

Cons:
- The average Windows user of DeerLab will experience a somewhat slower performance without the MKL backend. (edited)
