### ISSUE TITLE
Wrong fit parameter for background-only fit

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#34]
The following script fits a background-only signal with `fitsignal`. The fit is succesfull, and `fit.B` looks correct. But `fit.bgparam` is wrong.

```python
#%%
import deerlab as dl
import numpy as np
import matplotlib.pyplot as plt
#%%
t = np.linspace(0,5,100)
r = np.linspace(2,6,200)
k = 0.2
B = dl.bg_exp(t,k)

fit = dl.fitsignal(B,t,r,None,dl.bg_exp,dl.ex_4pdeer,uqanalysis=False)

B2 = dl.bg_exp(t,fit.bgparam)

# %%
plt.plot(t,B,'.',label='data (bgparam = {})'.format(k))
plt.plot(t,fit.B,label='fit.B')
plt.plot(t,B2,label='fit.bgparam={}'.format(fit.bgparam))
plt.legend()
```

**Comment by luisfabib** [comment]
The explanation is the same as in #26. The fit is actually correct, `fitsignal` does not fit

 `B(k) = exp(-k*t)` 

but

`B(t,lam) = exp(-lam*k*t)`
 
and analogously for all other background models. Of course for this case the fit is ambiguous since the `lam` and `k` parameters overdetermine the data.

This is inherent to the underlying model of `fitsignal`. If you want to fit a pure background function with no regard to the `lam` parameter then `fitparamodel` should be used.

**Comment by stestoll** [comment]
I see the point of including `lambda` in a physical background model like `bg_hom3d` that depends on spin concentration. But I am not so sure it makes sense in phenomenological models like `bg_exp` or the polynomial models.

**Comment by stestoll** [comment]
See #36.
