### ISSUE TITLE
Remove lambda parameter from phenomenological background models

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#36]
Current background models fall into two categories:
- physical: `bg_hom3d`, `bg_hom3dex`, and `bg_homfractal`.
- phenomenological: `bg_exp`, `bg_strexp`, `bg_sumstrexp`, `bg_prodstrexp`, `bg_poly1`, `bg_poly2`, `bg_poly3`.
All background models take `lambda` as a third input parameter and include it in some way into the calculation.

Physical models are derived from first-principles spin dynamics. Therefore, they do depend on the bulk spin concentration `c` and on the inversion efficiency `lambda`.

However, the phenomenological models do not have any spin-physical basis and are just shapes used to fit the time-domain decay attributed to the matrix spins. Therefore, they should not depend on `lambda`.

**Comment by luisfabib** [comment]
Well it depends on how we interpret the functionality of `fitsignal`. This function is the only DeerLab function thus far that relies on a hard-coded theoretical model of DEER signals (i.e. the multipathway theory). Therefore it should make sense that everything has some physical sense. 

As mentioned, `bg_hom3d`, `bg_homfractal` and `bg_hom3dex` are the only models whose parameters are actual physical constants. As per the model, these require the `lambda` parameter in order to properly model the signal. 

Now, while `bg_exp` and `bg_strexp` are phenomenological models, if the `lambda` is used for them, they become also physical models as they basically wrap some of the physical constants in  `bg_hom3d` and `bg_homfractal` into numerical decay rates. This is basically the reason for passing `lambda` in those models. 

I agree that for the other phenomenological models this makes less (or no) sense. However, these models do not have much context anyway in a function such as `fitsignal`. 

IMO since `fitsignal` is a function based on a strict model, I would prefer not to remove this functionality.

**Comment by stestoll** [comment]
This issue needs to be decided independent of what consequences it has for `fitsignal` and other functions. It is about the nature of the background models, which do fall into the two classes mentioned above.
