### ISSUE TITLE
Plot method of FitResult not working properly in MacOS

### ISSUE THREAD

**Issue by luisfabib** [JeschkeLab/DeerLab#74]
The `plot()` method of the `FitResult` object seems to not display properly on MacOS systems as reported by a user. 

The following MWE:
```python
filepath = ‘/xx/.DTA'
t,V = dl.deerload(filepath)
V = dl.correctphase(V)
t = dl.correctzerotime(V,t)
r = np.linspace(1.5,7,len(t))
 
fit = dl.fitsignal(V,t,r,'P',dl.bg_hom3d,dl.ex_4pdeer, verbose=True)
fit.plot()
```
seems to result in only the fit being shown, but not the original data and confidence intervals.

**Comment by laenan8466** [comment]
Hi,
I would like to discuss another matter where I'm not sure how to interpret. It is about the `fitResult.scale` parameter.

Afaik this is a factor that the fit of the trace gets scaled (see `fitsignal.py`, line 440).
```python
Vfit = [scale*K@Pfit for K,scale in zip(Ks,scales)]
```
For plotting (see `_display_results`-function of `fitsignal.py`) the experimental data `Vexp` doesn't get scaled with this factor lateron. Now I'm confused, if one would had to scale `Vexp` as well or not. Can you comment on this @luisfabib?

Cheers,
Dennis

**Comment by luisfabib** [comment]
Hi Dennis, indeed the scaling in the (build-in) plots of `fitsignal` was bugged. 

The `fitResult.scale` was not being taken into account. While the latest release still has this bug, we fixed this with e36b6ba0f655379b5541a6226fc50a0616c2a417, and should be patched in soon after the PR is merged. 

For plotting manually, the data should be scaled down or the fit scaled up by `fitResult.scale`, respectively.

**Comment by laenan8466** [comment]
Gnah, havn't seen that. Tried all combinations in advance but not that one. Now my plot behaves as it should. :-)
![grafik](https://user-images.githubusercontent.com/21331242/110154883-1815d980-7de5-11eb-8025-c69174003a9a.png)

Couldn't we/you solve that in a way, where the output 'fits' to the input in a future version? Or was that fixed as well? :-)

To your plot command: isn't it the other way around? At least that is what I did for the successful plots.

And now, enjoy your weekend!

**Comment by laenan8466** [comment]
Hey @luisfabib!
So, I guess I found an error now, but not sure if it is my fault or s.th. wrong with the outputs of fitsignal.

## Minimal Working example
I compared the output of `fit.plot()` and my 'manual' plot, using the same layout as in `fit.plot()`.

### Requirements
- For the tests I used https://github.com/JeschkeLab/DeerLab/commit/e36b6ba0f655379b5541a6226fc50a0616c2a417.
  - A small change is to `fitsignal.py`. Remove/Comment line 611:
    ```python
            # plt.show()
    ```
    This is important so that axs can be manipulated afterwards. I would recommend to skip the `plt.show()` command anyway, or manipulation of the returned axis isn't possible (at least for me). In my IDE (Spyder) plots are shown after running a script/command by default.
- Use the [two files in this MWE](https://github.com/JeschkeLab/DeerLab/files/6092939/LaserIMD_MWE.zip). They include a `LaserIMD_MWE.pkl` file with the data and the `LaserIMD_MWE.py` script.
- Run the `LaserIMD_MWE.py` script to get two Graphs.

### Output
#### Output from `fit.plot()`
![grafik](https://user-images.githubusercontent.com/21331242/110164906-582f8900-7df2-11eb-95f0-2a943820b485.png)

#### Output from manual plotting
![grafik](https://user-images.githubusercontent.com/21331242/110164918-5c5ba680-7df2-11eb-8b91-5f55cfffcdeb.png)

### Result
- There is an issue with my Background fit CIs. Im not sure what the issue is, but this is not the main problem. 
- The distance distribution is identical
- The fit to the trace (`Vfit`) is identical in both plots.
- There is an **offset in the experimental data** (`Vexp`)

To me the main issue is the last point. It is not clear to my, why this error occurs, but in this way it is not possible to plot/use the data in manually plotted figures.
The `fit.scale` property was only used for scaling of the `Bfit`. For plotting it was not necessary.

Thanks in advance for your help. I guess there will be some stupid error in my plotting/ handling of the data.

Dennis

**Comment by luisfabib** [comment]
@laenan8466  as always excellent issue-reporting!! I will look into the different issues. Feel always free to open as many issues as you want/need. 

As discussed in #78 we are gonna add output variables for scaled/unscaled variables to avoid most of these issues.

A short explanation on why I programmed prescaling of the signals. When doing global optimization, if you have multiple signals of a very different scale, the residual vector during the optimization would be largely heteroskedasticit and result in one of the signals dominating the fit. Additionally, pre-scaling avoids overflow issues in certain models.
