### ISSUE TITLE
diststats: behavior if r and P are swapped

### ISSUE THREAD

**Issue by stestoll** [JeschkeLab/DeerLab#90]
The correct input argument order for `diststats` is `diststats(r,P)`. If called with swapped arguments, `diststats(P,r,...)`, it runs, but returns meaningless results. Should `diststats` error if this situation is encountered?

**Comment by luisfabib** [comment]
Yes, it should. However, the issue here is being able to differentiate the syntax `diststats(r,P)` from `diststats(P,r)`. 

Since distinguishing both must be done based on numerical arguments, the only solution I see is to identify `r` as a vector that must be a monotonously increasing vector. This would clash if `P` was a distribution based on a monotonously increasing parametric model.

**Comment by luisfabib** [comment]
I pushed a change to #91 adding this.

**Comment by stestoll** [comment]
Looks good to me
